// Generated by CoffeeScript 1.10.0
(function() {
  var Episode, Errors, Promise, Scraper, SearchResult, Validation, _, cheerio, needle;

  Promise = require('bluebird');

  needle = Promise.promisifyAll(require('needle'));

  cheerio = require('cheerio');

  _ = require('lodash');

  Errors = require('./errors');

  Validation = require('./provider/validation');

  needle.defaults({
    follow_max: 10
  });

  SearchResult = (function() {
    function SearchResult(object) {
      var ref, ref1;
      this.seriesName = object.seriesName, this.seriesUrl = object.seriesUrl, this.searchProvider = object.searchProvider, this.episodes = (ref = object.episodes) != null ? ref : [], this.isSpecial = (ref1 = object.isSpecial) != null ? ref1 : false;
    }

    return SearchResult;

  })();

  Episode = (function() {
    function Episode(object) {
      this.number = object.number, this.title = object.title, this.url = object.url, this.searchProvider = object.searchProvider;
    }

    return Episode;

  })();

  Scraper = (function() {
    function Scraper() {
      this.providers = {};
    }

    Scraper.prototype.use = function(provider) {
      if (Validation.Logic.ValidateProvider(provider)) {
        this.providers[provider.name] = provider;
        return provider.initialize();
      }
    };

    Scraper.prototype.search = function(name, provider) {
      return this.fetchSearchResult(name, this.providers[provider]);
    };

    Scraper.prototype.searchAll = function(name) {
      return Promise.map(Object.keys(this.providers), (function(_this) {
        return function(provider) {
          return _this.fetchSearchResult(name, _this.providers[provider]);
        };
      })(this));
    };

    Scraper.prototype.fetchSearchResult = function(query, provider) {
      return provider._methods.search(query).then(function(body) {
        var $, list;
        $ = cheerio.load(body);
        list = $(provider.search.list);
        list = list.map(function(i, el) {
          return new SearchResult({
            seriesName: provider.search.row.name($(el)),
            seriesUrl: provider.search.row.url($(el)),
            searchProvider: provider
          });
        }).get();
        return list = _.filter(list, function(item) {
          return item.seriesName.toUpperCase().indexOf(query.toUpperCase()) > -1;
        });
      });
    };

    Scraper.prototype.fetchSeries = function(searchResult) {
      return needle.getAsync(searchResult.seriesUrl).then(function(resp) {
        var $, episodes;
        $ = cheerio.load(resp.body);
        episodes = $(searchResult.searchProvider.series.list);
        episodes = episodes.map(function(i, el) {
          var number;
          if (searchResult.searchProvider.series.row.number == null) {
            number = i + 1;
          } else {
            number = searchResult.searchProvider.series.row.number($(el));
          }
          return new Episode({
            title: searchResult.searchProvider.series.row.name($(el)),
            url: searchResult.searchProvider.series.row.url($(el)),
            number: number,
            searchProvider: searchResult.searchProvider
          });
        }).get();
        searchResult.episodes = episodes;
        return searchResult;
      });
    };

    Scraper.prototype.fetchVideo = function(episode) {
      return needle.getAsync(episode.url).then(function(resp) {
        var $;
        $ = cheerio.load(resp.body);
        return episode.searchProvider.episode($, resp.body);
      });
    };

    return Scraper;

  })();

  module.exports = Scraper;

}).call(this);
